CREATE SCHEMA IF NOT EXISTS schema1; -- todo role
CREATE SCHEMA IF NOT EXISTS schema2; -- todo role

CREATE TABLE IF NOT EXISTS schema1.USERS (
  ID_ INTEGER PRIMARY KEY,
  LOGIN_NAME_ VARCHAR(30) NOT NULL UNIQUE,
  FIRST_NAME_ VARCHAR(30) NOT NULL,
  LAST_NAME_ VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS schema2.TASKS (
  ID_ INTEGER PRIMARY KEY,
  USER_NOTE_ VARCHAR(255) NOT NULL,
  TASK_DATA_ TEXT NOT NULL,
  ACQUIRED_BY_ INTEGER NOT NULL,
  CREATED_BY_ INTEGER NOT NULL,
  CONSTRAINT FK_ACQUIRED_BY_ FOREIGN KEY(ACQUIRED_BY_) REFERENCES schema1.USERS(ID_),
  CONSTRAINT FK_CREATED_BY_ FOREIGN KEY(CREATED_BY_) REFERENCES schema1.USERS(ID_)
);

-- TODO INDEXES